name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 升级到 v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18         # 推荐使用 LTS 版本
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          {
            echo "VITE_GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}";
            echo "VITE_TWIKOO_ID=${{ secrets.VITE_TWIKOO_ID }}";
            echo "VITE_LEANCLOUD_ID=${{ secrets.VITE_LEANCLOUD_ID }}";
            echo "VITE_LEANCLOUD_KEY=${{ secrets.VITE_LEANCLOUD_KEY }}";
            echo "VITE_LEANCLOUD_SERVER=${{ secrets.VITE_LEANCLOUD_SERVER }}";
            echo "VITE_CLARITY_ID=${{ secrets.VITE_CLARITY_ID }}";
            echo "VITE_UTTERANCES_CODE=${{ secrets.VITE_UTTERANCES_CODE }}";
          } > .env                # 使用重定向一次性写入，避免多次追加

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 默认使用内置 Token
          external_repository: Kemeow815/Kemeow815.github.io
          publish_branch: main
          publish_dir: ./dist
          cname: myblog.kemeow.cn
          commit_message: "Deploy: ${{ github.sha }}"

      # 移除冗余的输出步骤（通常不需要）
